# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
    - name: Show available destinations
      run: xcodebuild -scheme Transmission -showdestinations
    - name: Build for Catalyst
      run: xcodebuild -scheme Transmission -destination 'platform=macOS,variant=Mac Catalyst' build
    - name: Build for iOS
      run: xcodebuild -scheme Transmission -destination 'platform=iOS Simulator,name=iPhone 16' build
